name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo snap install dmd --classic
    - name: Build brolang
      run: |
        sudo chown root:root /
        make brolang
        chmod +x run
    - name: Run examples
      run: |
        ./run examples/hello.bro
        ./run examples/fibronacci.bro
        ./run examples/mandelbro.bro
